//Get users route 
get http://localhost:3000/user-api/users

### get a specific user by id 



### creating user
post http://localhost:3000/user-api/user
Content-Type: application/json

{
    "id":12,
    "name":"praneeth",
    "age":24
}